server:
  port: 8080

spring:
  application:
    name: financeProcessing

  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: finance_user
    password: Finance@218
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    time-zone: UTC

  jwt:
    secret: finance_super_secret_key_must_be_at_least_256_bits_long_for_hs256
    expiration: 86400000   # 24 hours